name: Lint Backend

on: push

permissions:
  contents: read
  statuses: write
  checks: write

jobs:
  lint-backend:
    name: Lint Python with Black and Flake8
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11' # or your project's version

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install black flake8

      - name: Run Black (check formatting)
        run: black . --check

      - name: Run Flake8 (linting)
        run: flake8 .
