name: Lint Frontend

on: push

permissions:
  contents: read
  statuses: write
  checks: write

jobs:
  lint-frontend:
    name: Lint Frontend with ESLint
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20' # or match your project

      - name: Install dependencies
        run: npm ci

      - name: Run ESLint
        run: npx eslint . --ext .js,.jsx,.ts,.tsx --max-warnings=0
