name: Super-Linter

on: push

permissions:
  contents: read
  statuses: write
  checks: write

jobs:
  super-lint:
    name: SuperLint code base
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Run Super-Linter
        uses: super-linter/super-linter@v6
        env:
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          JSCPD_MAX_PERCENTAGE: 1.5
